version: '3'

services:
  nginx:
    image: nginx:1.13.8
    networks:
       - my-network
    ports:
      - "80:80"
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/nginx/server.conf:/etc/nginx/conf.d/default.conf
      - ./docker/nginx/log:/var/log/nginx
      - ./deploy_app:/var/www/app
    depends_on:
      - php
    container_name: nginx

  php:
    build: ./docker/php
    networks:
       - my-network
    volumes:
      - ./docker/php/php.ini:/usr/local/etc/php/conf.d/php.ini
      - ./docker/php/www.conf:/usr/local/etc/php-fpm.d/www.conf
      - ./deploy_app:/var/www/app
    container_name: php

  mysql:
    image: mysql:5.7.21
    environment:
      MYSQL_ROOT_PASSWORD: root
    networks:
       - my-network
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql
      - ./docker/mysql:/etc/mysql/conf.d
    container_name: mysql

  memcached:
    image: memcached:1.5.4
    networks:
       - my-network
    ports:
      - "11211:11211"
    container_name: memcached

  redis:
    image: redis:3.2.11
    networks:
      - my-network
    ports:
      - "6379:6379"
    container_name: redis

networks:
  my-network:

volumes:
  db-data:
