version: '3'

services:
  nginx:
    image: nginx:1.13.8
    networks:
       - my-network
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/server.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/log:/var/log/nginx
      - ../deploy_app:/var/www/app
    container_name: nginx

  # php:
  #   image: php7.0.27-fpm
  #   container_name: php

  mysql:
    image: mysql:5.7.21
    environment:
      MYSQL_ROOT_PASSWORD: root
    networks:
       - my-network
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql
      - ./mysql:/etc/mysql/conf.d
    container_name: mysql

  memcached:
    image: memcached:1.5.4
    networks:
       - my-network
    ports:
      - "11211:11211"
    container_name: memcached

  # redis:
  #   image: redis:3.2.11
  #   networks:
  #     - my-network
  #   container_name: redis

networks:
  my-network:

volumes:
  db-data:
